Bugfix for Exception 8:39 am Dec 22th 2015 because of incorrect barcode format
A NoMethodError occurred in submissions#create:

 undefined method `+' for nil:NilClass
 [RAILS_ROOT]/app/models/barcode.rb:101:in `calculate_checksum'