Fix method missing exception on policy accession
Recent exception:
A NoMethodError occurred in studies#policy_accession:

 undefined method `submit_policy_for_user' for #<NoAccessionService:0x0000000f6d9750 @study_id=1834>
Did you mean?  submit_dac_for_user
              submit_sample_for_user
              submit_study_for_user
 app/controllers/studies_controller.rb:303:in `block in policy_accession'

We've got handling in place for most the other inappropriate accessions, this one just got missed off.