flip flop this back to 'options' rather than 'capabilities' - 'capabilities' wasn't being recognized (undefined method 'add_preference' for nil:NilClass (NoMethodError)) - probably due to selenium-webdriver update to 4.1.0 - something not quite right here, as I get a deprecation warning for 'options', asking me to use 'capabilities'